name: app_generator
description: This package for generating GetX controllers.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.2.0
  mustache_template: ^2.0.0
  path: ^1.8.0